/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _tabito_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface documentRow {
  'authorId': number|bigint;
  'id'?: number|bigint;
  'shareStatus': string;
  'title': string;
}
export interface sentenceRow {
  'authorId': number|bigint;
  'documentId': number|bigint;
  'id'?: number|bigint;
  'jsonEncoded': string;
  'plain': string;
  'plainSha256': string;
}
export interface sentenceShareRow {
  'sentenceId': number|bigint;
  'userId': number|bigint;
}
export interface userRow {
  'displayName': string;
  'id'?: number|bigint;
}
export interface userProviderRow {
  'providerId': any;
  'providerName': any;
  'userId': number|bigint;
}
