/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _tabito_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface documentRow {
  'docName': string;
  'id'?: number|bigint;
  'plain': string;
}
export interface sentenceRow {
  'id'?: number|bigint;
  'jsonEncoded': string;
  'plain': string;
  'plainSha256': string;
}
