/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _tabito_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface connectedWordsRow {
  'componentId'?: string;
  'type'?: string;
  'wordId'?: string;
}
export interface documentRow {
  'docName': string;
  'id'?: number|bigint;
  'plain': string;
}
export interface jmdictRow {
  'addedMs': number;
  'json': string;
  'wordId'?: string | null;
}
export interface sentenceRow {
  'id'?: number|bigint;
  'jsonEncoded': string;
  'plain': string;
  'plainSha256': string;
}
